package com.arny.mobilecinema.domain.interactors.jsoupupdate

object Selectors {
    const val TYPE_SERIALS = "serials"
    const val TYPE_FILMS = "films"
    const val TYPE_ALL = "all"
    const val SERIALS_URL = "/serials"
    const val FILMS_URL = "/"
    const val ALL_PAGES = ".pages a:last-child"
    const val FILM_LINK = ".film>a"
    const val FILM_LINK_ATTR = "href"
    const val PAGE = "body"
    const val TITLE = ".blc .acat"
    const val IMG = ".screen img"
    const val SRC_ATTR = "src"
    const val RATING = "#rating span"
    const val INFO = ".screen2 table tr"
    const val DESCRIPTION = ".filmopis.screen3>p"
    const val PAGE_SCRIPT = "script:containsData(playerjs)"
    const val KINO_HD_SCRIPT = "script:containsData(kinohd)"
    const val KINO_HD_SCRIPT2 = "script:containsData(title:)"
    const val KINO_HD_IFRAME = "iframe"
    const val KINO_REGEXP = "(?<=ids == \"kino\").*?Playerjs\\(\"(.*?)\""
    const val SIMPLE_REGEXP = "Playerjs\\(\"(.*?)\""
    const val IFRAME_SRC_REGEXP = "(?<=iframe loading=\"lazy\").*src=\"(.+)\"\\s*(?=title)"
    const val TRAILER_REGEXP =
        "(?<=[^ids==\"kino\"]).*Playerjs\\(\"(.*)\".*(?=trail.setAttribute\\(\"class\", \"current\"\\))"
    const val DASH_REGEXP = "dash:\\s\"(.*?)\""
    const val HLS_REGEXP = "hls:\\s\"(.*?)\""
    const val POSTER_REGEXP = "poster:\\s\"(.*?)\""
    const val SEASONS = ".blms .tl2 a"
    const val EPISODES_REGEXP = "\\((\\d+)(\\sиз\\s\\d+)?\\)"
    const val SEASONS_ATTR = "href"
    const val EPISODES = ".blm a"
    const val ALL_CINEMA_LINKS = ".blms .tl2 a:contains(Скачать)"
    const val DOWNLOAD_LINK = ".blm a:contains(Скачать)"
    const val HREF_ATTR = "href"
    const val SERIAL_IFRAME = "iframe[src~=http]"
    const val IFRAME_ATTR = "src"
    const val SERIAL_IFRAME_SCRIPT = "script:containsData(iframe)"
    const val SERIAL_IFRAME_SCRIPT_SEASONS = "script:containsData(seasons)"
    const val SERIAL_EPISODES_REGEXP = "seasons:\\s?(\\[\\{.*\\]\\}\\])"
    const val PROXIES = ".table-proxy-list"
    const val PROXIES_REGEXP = "(\\b\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3}\\s\\d{2,5}\\b) Russian Federation http"
    const val PROXY_REGEXP = "(\\b\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3}\\:\\d{2,5}\\b)"
}