package com.arny.mobilecinema.domain.interactors.jsoupupdate

object Selectors {
    const val TYPE_SERIALS = "serials"
    const val TYPE_FILMS = "films"
    const val TYPE_ALL = "all"
    const val SERIALS_URL = "/serials"
    const val FILMS_URL = "/"
    const val ALL_PAGES = ".pages a:last-child"
    const val FILM_LINK = ".film>a"
    const val FILM_LINK_ATTR = "href"
    const val PAGE = "body"
    const val TITLE = ".blc .acat"
    const val IMG = ".screen img"
    const val SRC_ATTR = "src"
    const val RATING = "#rating span"
    const val INFO = ".screen2 table tr"
    const val DESCRIPTION = ".filmopis.screen3>p"
    const val COMMENTS_LINK = "a[href*=/comm/]"
    const val COMMENTS_COUNT = "$COMMENTS_LINK .cb"
    const val COMMENTS_TITLE = ".comm_title"
    const val COMMENTS_TEXT = ".comm_main"
    const val COMMENTS_AUTHOR = "a[href*=/user/]"
    const val COMMENTS_PAGES = ".pages a"
    const val PAGE_SCRIPT = "script:containsData(playerjs)"
    const val KINO_HD_SCRIPT = "script:containsData(kinohd)"
    const val KINO_HD_SCRIPT2 = "script:containsData(title:)"
    const val KINO_REGEXP = "(?<=ids == \"kino\").*?Playerjs\\(\"(.*?)\""
    const val SIMPLE_REGEXP = "Playerjs\\(\"(.*?)\""
    const val IFRAME_SRC_REGEXP = "(?<=iframe loading=\"lazy\").*src=\"(.+)\"\\s*(?=title)"
    const val SEASONS = ".blms .tl2 a"
    const val EPISODES_REGEXP = "\\((\\d+)(\\sиз\\s\\d+)?\\)"
    const val SEASONS_ATTR = "href"
    const val EPISODES = ".blm a"
    const val ALL_CINEMA_LINKS = ".blms .tl2 a:contains(Скачать)"
    const val DOWNLOAD_LINK = ".blm a:contains(Скачать)"
    const val HREF_ATTR = "href"
    const val SERIAL_IFRAME = "iframe[src~=http]"
    const val IFRAME_ATTR = "src"
    const val SERIAL_IFRAME_SCRIPT = "script:containsData(iframe)"
    const val SERIAL_IFRAME_SCRIPT_SEASONS = "script:containsData(seasons)"
    const val SERIAL_EPISODES_REGEXP = "seasons:\\s?(\\[\\{.*\\]\\}\\])"
}